#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 <backend-name>"
    exit 1
fi

BACKEND=$1

XS_PATH="drivers/$BACKEND/status"

CURRENT_STATUS="unknown"

while true; do
    if [ x$CURRENT_STATUS = x"unknown" ]; then
        xenstore-watch -n1 $XS_PATH
    else
        xenstore-watch -n2 $XS_PATH
    fi

    STATUS=`xenstore-read $XS_PATH`

    echo "'$BACKEND' status is '$STATUS'."
    if [ x$STATUS != x$CURRENT_STATUS ]; then
        if [ x$STATUS = x"ready" ]; then
            echo "Sending systemd-notify status 'READY' for backend '$BACKEND'."
            systemd-notify --ready
        elif [ x$STATUS = x"dead" -a x$CURRENT_STATUS != x"unknown" ]; then
            echo "Failing to notify '$BACKEND' unavailability. Will be restarted soon ..."
            exit 1;
        fi
    fi

    CURRENT_STATUS=$STATUS
done
